export const CATEGORY_ICONS: Record<string, string> = {
  AI: '🤖',
  'Machine Learning': '🧠',
  'Data Science': '📊',
  'Web Development': '🌐',
  'Frontend': '🖥️',
  'Backend': '🗄️',
  'Fullstack': '🧩',
  'DevOps': '⚙️',
  'Microservices': '🔗',
  'Cloud Computing': '☁️',
  'Testing': '🧪',
  'Quality Assurance': '✅',
  'Security': '🔐',
  'Databases': '🗃️',
  'Automation': '🤖',
  'Tooling': '🛠️',
  'Learning': '📚',
  'Open Source': '🌍',
  'Mobile Development': '📱',
  'Game Development': '🎮',
  'Virtual Reality': '🕶️',
  'Augmented Reality': '📸',
  'System Design': '🏗️',
  'Software Architecture': '🏛️',
  'Data Engineering': '🚰',
  'Authentication': '🔑'
}
